### PR TITLE
A minimal set of guide stat plot improvements

### PR DESCRIPTION
**Pull request by jeanconn**
Plot fixes

   - Fixes label placement so they are on the plots
   - Updates obc bad fraction plot so it is just obc bad fraction (and not a combined quantity of obc bad fraction and not tracking)
   - Tweaks ylims so data has a little more padding and should be basically fixed between reports
   - Adds colorization for ERs vs ORs on fraction plots

### CODE REVIEW

**Comment by jeanconn** [comment]
new_stat_page

**Comment by jeanconn** [comment]
New plots also in the new dev output at

http://cxc.cfa.harvard.edu/mta/ASPECT/gui_stat_reports_dev/2018/Q1/

**Comment by taldcroft** [comment]
Awesome!  This is very illuminating.  Just one niggle, which is that `OR` and `ER` are actually acronyms that need to be capitalized.

**Comment by jeanconn** [comment]
I'm really not sure what the obc status vs mag plot is showing us at this point...  just how the IR and SP algorithms are a bit more likely to end up testing true for fainter stars?

**Comment by jeanconn** [comment]
I fixed the niggle.  Are these good to go for this PR @taldcroft ?

**Review by taldcroft — APPROVED** [review]

**Pull request merged**
